### ISSUE TITLE
velocity units incorrect when reading IRAM/gildas FITS into miriad

### ISSUE THREAD

**Issue by mpound** [astroumd/miriad#6]
I have some IRAM cubes created by gildas that I have read into miriad.  They appear to have correct headers with velocity units in m/s but when read in with the FITS task, CUNIT3 is interpreted as km/s.    For example in the attached FITS file,

CRVAL3 = 25 km/s
CDELT3 = -0.13 km/s
CRPIX3 = 113.4 

which would be the correct values for these data.  But imhead sees:
crval3   Coordinate value of ref. pixel:                          2.5\x10\u4\d
cdelt3   Increment between pixels:                                      -132.8

I tried puthd in=file.fits/CUNIT3='m/s' but that made no difference.

[m16_13co10.fits.gz](https://github.com/astroumd/miriad/files/6631871/m16_13co10.fits.gz)

**Comment by teuben** [comment]
FYI: CASA would not read in the file, apparently "The GLS projection is deprecated. Use SFL instead.".   GILDAS people should be notified about it.   For LMT we also use the "SFL" projection.  I edited the header, then it's fine, and the header shows the correct (km/s) units for the header.   At least CASA is user friendly and uses km/s to display values to the user.

**Comment by teuben** [comment]
(added via Marc):    according to https://fits.gsfc.nasa.gov/standard30/fits_standard30aa.pdf
Table 25 page 32, VRAD is m/s

**Comment by teuben** [comment]
I hacked fits.for so it also sees VRAD (in addition to the previously established VELO and FELO). It's hard to imagine this will bite anybody back, though the table in co.for suggests there may be more spectral axes.   VOPT  might be missing . 
To  be continued?

**Comment by mpound** [comment]
I tested against the FITS file attached in the issue submission.   The velocities are now correct.  Thanks!
